### PR TITLE
JEP Integration with DH2

### PR DESCRIPTION
**Pull request by Rezzo64**
Progressing through the petmodsdh integration, will un-draft this once completed

### CODE REVIEW

**Comment by Rezzo64** [comment]
我无意中也加点儿新 Learnset data

**Comment by PlagueVonKarma** [comment]
你还好吗？😅

**Comment by Rezzo64** [comment]
没事！

**Comment by Rezzo64** [comment]
This is in a state worth merging now. Summary:
- pokedex.ts completed up to a certain amount (some species still missing)
- learnsets.ts completed up to the same amount of species as above, new moves added to movepools of existing and new species
- types.ts is done
- formats-data adds all new fully evolved species to OU. All previous species moved to NFE or LC depending on how they have been affected by the new additions

**Comment by Rezzo64** [comment]
This is all done now (with testing), merge whenever

**Comment by PlagueVonKarma** [comment]
谢谢你的帮助！

**Pull request merged**
